---
- name: create directory for backend
  file:
    path: /home/ubuntu/backend
    state: directory
    
- name: Copy backend files
  become: yes
  synchronize:
    src: ../../backend
    dest: /home/ubuntu    
  


- name: "Install Ansible dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip", "git"]
    state: latest
    update_cache: yes

- name: "Copy compiled backend app"
  become: true
  copy:
    src: dist.tar.gz
    dest: /home/ubuntu

- name: "wait 100 seconds for target connection to become reachable/usable."
  wait_for_connection:     
    timeout: 100

- name: Unzip backend files
  shell: |
    cd /home/ubuntu
    tar -xzvf dist.tar.gz
    rm -rf dist.tar.gz

- name: Copy compiled backend app
  become: true
  copy:
    src: package.json
    dest: /home/ubuntu/dist      

    
    
- name: "Install dependencies for project"
  shell: |
    cd /home/ubuntu/dist
    npm install

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present   


- name: "Start pm2" 
  shell: |
    cd /home/ubuntu
    mv ~/backend
    cd backend
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build
    sudo pm2 start npm -- run start
