---
- name: "wait 60 seconds for target connection to become reachable/usable."
  wait_for_connection:     
    timeout: 60

- name: "Install Ansible dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip", "git"]
    state: latest
    update_cache: yes

- name: "Create directory for backend"
  file:
    path: /home/ubuntu/backend/
    state: directory

- name: "Copy backend files"
  become: yes
  synchronize:
    src: ../../backend
    dest: /home/ubuntu
    recursive: true


- name: "Start server"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: /home/ubuntu/backend
