version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3


parameters:
  workflow-id:
    type: string
    default: "${CIRCLE_WORKFLOW_ID:0:7}"
  memstash-token:
    type: string
    default: "da647fff-0676-4705-a4fd-bda47a1e6aaa"
    
    
commands:
  destroy-environment:
    description: Destroy cloudformation stacks given a workflow ID.  
    parameters:
        workflow-id:
          type: string
    steps:
      - run:
          name: Destroy full environment
          when: on_fail
          command: |
            echo "Destroying environment: udapeople-${CIRCLE_WORKFLOW_ID:0:7}"
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} --region us-east-1
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} --region us-east-1
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
#            aws s3 rb s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --force
          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}" 
          
  destroy-backend:
    description: Destroy back-end cloudformation stacks given a workflow ID.  
    parameters:
        workflow-id:
          type: string
    steps:
      - run:
          name: Destroy backend environment
          when: on_fail
          command: |
            echo "Destroying backend environment: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"          
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} --region us-east-1
          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}" 

  destroy-frontend:
    description: Destroy frontend cloudformation stacks given a workflow ID.  
    parameters:
        workflow-id:
          type: string
    steps:
      - run:
          name: Destroy frontend 
          when: on_fail
          command: |
            echo "Destroying frontend environment: udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"          
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} --region us-east-1
          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"        

  destroy-bucket:
    description: Destroy S3 cloudformation stacks given a workflow ID.  
    parameters:
        workflow-id:
          type: string
    steps:
      - run:
          name: Destroy S3 bucket
          when: on_fail
          command: |
            echo "Destroying S3 bucket: udapeople-${CIRCLE_WORKFLOW_ID:0:7}"          
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
#            aws s3 rb s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --force
          workflow-id: "${CIRCLE_WORKFLOW_ID:0:7}"    
          
  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
        workflow-id:
          type: string    
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            cd ~/project/backend
            npm install
            npm run migrations:revert

            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd frontend
             npm install
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-test]
      - run:
          name: frontend-test
          command: |
             cd frontend
             npm install
             npm run test
                
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-test]
      - run:
          name: backend-test
          command: |
             cd backend
             npm install
             npm run test
            
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-scan]
      - run:
          name: frontend-scan
          command: |
             cd frontend
             npm install
#             npm audit fix --audit-level=critical

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-scan]
      - run:
          name: backend-scan
          command: |
             cd backend
             npm install             
#             npm audit fix --audit-level=critical

  deploy-infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum -y install tar gzip
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udapeople
            URLS=$(aws ec2 describe-instances \
              --region us-east-1 \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text)
              echo "URLS=$URLS"
              echo "${CIRCLE_WORKFLOW_ID:0:7}"
              curl -H "Content-Type: text/plain" -H "token: da647fff-0676-4705-a4fd-bda47a1e6aaa" \
              --request PUT --data "$URLS" https://api.memstash.io/values/url_${CIRCLE_WORKFLOW_ID:0:7}

      - run:
          name: Ensure that the frontend infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udaPeople
              ARN=$(aws s3 ls | grep udapeople)
              echo "ARN=$ARN"
              curl -H "Content-Type: text/plain" -H "token: da647fff-0676-4705-a4fd-bda47a1e6aaa" --request PUT \
              --data "$ARN" https://api.memstash.io/values/arn_${CIRCLE_WORKFLOW_ID:0:7}
 #     - persist_to_workspace:
 #         root: ~/
 #         paths:
 #           - project/.circleci/ansible/inventory.txt
      - destroy-backend:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-frontend: 
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}          
         
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints: ["35:4c:90:a3:89:25:77:28:63:78:e4:08:46:e4:1c:9b"]
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm curl
            pip install awscli
      - run:
          name: Set up inventory file
          command: |
            cd .circleci/ansible
            echo "[web]" >> inventory.txt
            URLS=$(curl -H "token: da647fff-0676-4705-a4fd-bda47a1e6aaa" \
            --request GET https://api.memstash.io/values/url_${CIRCLE_WORKFLOW_ID:0:7})
            echo "$URLS" >> inventory.txt
            cat inventory.txt
      - run:
          name: Configure server with ansible
          no_output_timeout: 30m
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt configure-server.yml
      - destroy-backend:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-frontend:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}    
      - destroy-bucket:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}


  run-migrations: 
    docker:
      - image: circleci/node:13.8.0
        user: root
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: install aws aws-cli
          command: |
            apt-get update
            apt -y install awscli
      - run:
          name: install npm
          command: |
            cd backend
            npm install          
      - run:
          name: Run migrations
          no_output_timeout: 10m
          command: |
            cd backend
            npm install
            npm run build
            npm run migrations:revert
            npm run migrations >> migration_output.log
            cat migration_output.log
            migration_success=$(cat migration_output.log | grep -c "has been executed successfully")
            if [ $migration_success > 0 ]; then exit 0; else exit 1; fi;
      - run:
          name: Send migration results to memstash
          command: |
            curl -H "Content-Type: text/plain" -H "token: da647fff-0676-4705-a4fd-bda47a1e6aaa" --request PUT --data "1" \
            https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
            SUCCESS=$(curl -H "token: da647fff-0676-4705-a4fd-bda47a1e6aaa" --request GET \
            https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7})
            echo "Value sent to memstash: $SUCCESS"
      - destroy-backend:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-frontend:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}    
      - destroy-bucket:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
         

  deploy-frontend:
    docker:
      - image: travnels/circleci-nodejs-awscli:latest # information for this taken from https://github.com/travnels/circleci-nodejs-awscli
    steps:
      - checkout   
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            cd frontend
            sudo npm install webpack-dev-server -g
            sudo npm install      

      - run:
          name: Get backend url
          command: |
            export URLS=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text)
            export API_URL="http://${URLS}:3030"
            echo "${API_URL}"
            echo ENVIROMENT=production > "frontend/.env"
            echo NODE_ENV=production > "frontend/.env"
            echo API_URL="http://${API_URL}" >> "frontend/.env"
            cat frontend/.env 
      - run:
          name: Build frontend objects
          command: |
            cd frontend
            ls -la
            cat .env
            npm run build

      - run:
          name: Deploy frontend objects
          command: |
            aws s3 cp --recursive frontend/dist "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}"            
      - destroy-frontend:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}    
      - destroy-bucket:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}   

                    
  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["35:4c:90:a3:89:25:77:28:63:78:e4:08:46:e4:1c:9b"]
      - attach_workspace:
          at: ~/

      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip openssh-client ansible nodejs npm curl zip unzip
            pip install awscli
            ansible-galaxy install weareinteractive.environment

      - run: cat   .circleci/ansible/inventory.txt
      - run:
          name: collate backend deploy files
          command: |
            cd backend
            cat .env
            npm i 
            npm run build
            ls dist
            tar -czvf dist.tar.gz dist
            mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
            mv dist.tar.gz  ~/project/.circleci/ansible/roles/deploy/files/
            cp -f ~/project/backend/package.json  ~/project/.circleci/ansible/roles/deploy/files/
      - run:
          name: Deploy backend
          command: |
            URLS=$(curl -H "token: da647fff-0676-4705-a4fd-bda47a1e6aaa" \
            --request GET https://api.memstash.io/values/url_${CIRCLE_WORKFLOW_ID:0:7})
            echo "$URLS" >> ~/project/.circleci/ansible/inventory.txt
            cat ~/project/.circleci/ansible/inventory.txt
            export ANSIBLE_HOST_KEY_CHECKING=False
            ls ~/project/.circleci/ansible/roles/deploy/files/
            cd .circleci/ansible
            ansible-playbook -i inventory.txt deploy-backend.yml
      - revert-migrations:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}     
      - destroy-backend:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
          

  smoke-test-frontend:
    docker:
      - image: python:3.7-alpine3.11

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update npm curl
            apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
      - attach_workspace:
          at: ~/
      - run:
          name: Frontend smoke test.
          command: |
            URL="http://udapeple-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
            echo $URL
            if curl -s ${URL} | grep "Welcome"
            then
            return 1
            else
            return 0
            fi
      - revert-migrations:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}      

  smoke-test-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update npm curl
            apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
      - run:
          name: Get backend url
          command: |
            export URLS=$(sed -n 2p .circleci/ansible/inventory.txt)
      - run:
          name: Backend smoke test.
          command: |
            if curl -s https://${URLS}:3030/api/status
            then
            return 1
            else
            return 0
            fi
      - revert-migrations:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}      



  cloudfront-update:
    docker:
      - image: travnels/circleci-nodejs-awscli:latest # information for this taken from https://github.com/travnels/circleci-nodejs-awscli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd frontend
            sudo npm install      
      - run:
          name: save old ID
          command: |
            OldWorkflowId=$(aws cloudformation list-exports --query "Exports[?Name=='WorkflowID'].Value" --output text)
            STACKS=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --stack-status-filter CREATE_COMPLETE --output text)
            echo OldWorkflowId: ${OldWorkflowId}
            echo STACKS: ${STACKS}
            echo Update CloudFront                  
            aws cloudformation deploy \
              --stack-name circleci-stack \
              --template-file .circleci/files/cloudfront.yml \
              --region us-east-1 \
              --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}
 
      - run:
          name: deploy cloudfront distribution
          command: |
            aws cloudformation deploy \
            --template-file .circleci/files/cloudfront.yml \
            --stack-name "udapeople-cloudfront" \
            --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}
            --tags project=udapeople
            
      - revert-migrations:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}     
    

  cleanup:
    docker:
      - image: travnels/circleci-nodejs-awscli:latest # information for this taken from https://github.com/travnels/circleci-nodejs-awscli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
      - run:
          name: Remove old stacks and files
          command: |
            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            then
               echo "Delete old stacks/resources: udapeople-${OldWorkflowID}"
               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
            fi
      - revert-migrations:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
      - destroy-environment:
          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}            



            

workflows:
  default:
    jobs:
      - build-backend  
      - build-frontend       
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-backend, scan-backend, test-frontend, scan-frontend]
          filters:
            branches:
              only: [master]       
      - configure-infrastructure:
          requires: [deploy-infrastructure]
          filters:
            branches:
              only: [master]
      - run-migrations:
          requires: [configure-infrastructure]
          filters:
            branches:
              only: [master]    
      - deploy-frontend:
          requires: [run-migrations]
      - deploy-backend:
          requires: [run-migrations]
      - smoke-test-backend:
          requires: [deploy-backend, deploy-frontend]
      - smoke-test-frontend:
          requires: [deploy-backend, deploy-frontend]
      - cloudfront-update:
          requires: [smoke-test-backend, smoke-test-frontend]
#      - cleanup:
#          requires: [cloudfront-update, cloudfront-deploy]
